export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  CONFLICT_VERSION: "CONFLICT_VERSION",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  WORKFLOW_INVALID_TRANSITION: "WORKFLOW_INVALID_TRANSITION",
  BRUTE_FORCE_LOCKED: "BRUTE_FORCE_LOCKED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];